# Extending image
FROM node:16.17.1-alpine3.16 as build

WORKDIR /usr/app
COPY ./ /usr/app

# Create app directory
#RUN mkdir -p /usr/src/app
#WORKDIR /usr/src/app

# Install app dependencies
#COPY package.json /usr/src/app/

# Install git
#RUN apk add --no-cache git

#RUN git config --global http.sslVerify false

# Install node modules
RUN npm install

#COPY . /app

# Bundle app source
#COPY . /usr/src/app

#ENV PRODUCTION_PORT 80
#ENV NODE_ENV production
#ENV PUBLIC_PATH "/"

RUN npm run build


FROM nginx:1.23.1-alpine
EXPOSE 80

COPY ./docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/app/dist /usr/share/nginx/html

RUN mkdir -p /var/www/cache