# Extending image
FROM node:18-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/

# Install git
RUN apk add --no-cache git

RUN git config --global http.sslVerify false

RUN cd /app; npm install

COPY . /app

# Bundle app source
COPY . /usr/src/app

# Port to listener
# Environment variables

EXPOSE 80
EXPOSE 443

ENV PRODUCTION_PORT 80
ENV NODE_ENV production

ENV PUBLIC_PATH "/"

RUN npm run build

CMD ["./app"]

FROM nginx:latest

LABEL maintainer="jviatge"

COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
#COPY ./cert /etc/nginx/

RUN mkdir -p /var/www/cache

EXPOSE 80
EXPOSE 443